version: '3.8'
services:
  mongodb:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_DATABASE: store-testdb
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro